### ISSUE TITLE
Can't load flash web site

### ISSUE THREAD

**Issue by asalogJDM** [chromelyapps/demo-projects#1]
Hi,

I try to load a flash web site with CefGlue gtk linux and i Don't know how to fix it.

I have enable flash, install pepperFlash, use no-zygote, …

Now i have the message "Right-click to run Adobe flash player", the right-click doesn't works. Maybe it's the web site is not allowed?

Any ideas or solutions?

Thanks

**Comment by mattkol** [comment]
@asalogJDM it is difficult to tell straightaway, but I can think of 3 ways this may happen.

1. Yes, it may be blocked. It could be cross-origin issue. In that case you may have to disable security. I just disabled security for new release - https://github.com/chromelyapps/Chromely/blob/8e04b48cc4e0a254be9e1d1d6f81a692a659becf/src/Chromely.CefGlue/Browser/CefGlueBrowser.cs#L202

2. If this issue is not security, you may have to register the url as an external domain - https://github.com/chromelyapps/Chromely/wiki/External-Url-Registration and see if this works.

3. If 1 and 2 do not work, then it means you have to handle the download. You can write a custom download handler. For more info on how to do that, please see Configuration page in the wiki (on Chromely repo) - https://github.com/chromelyapps/Chromely/wiki/Configuration#how-to-add-custom-handlers

Sample:
````csharp
ChromelyConfiguration config = ChromelyConfiguration
                              .Create()
                              .....
                             .RegisterCustomHandler(CefHandlerKey.DownloadHandler, typeof(CustomDownloadHandler));
                              ....

**Comment by mattkol** [comment]
@asalogJDM this may help  - https://magpcss.org/ceforum/viewtopic.php?f=6&t=12941.
