### ISSUE TITLE
Why isn't ChromelyVueCefGlue?

### ISSUE THREAD

**Issue by fendou** [chromelyapps/demo-projects#2]
When can have sample?

**Comment by mattkol** [comment]
@fendou no reason really why there is none. As at the time it was done I just ran out of bandwidth to continue and since no one asked its been this way since.

I am not sure if @Fiahblade has anything planned. But yes, at some point we will have all samples, just difficult to promise when.

If you need this urgently looking into [ChromelyVueCefSharp](https://github.com/chromelyapps/demo-projects/tree/master/angular-react-vue/ChromelyVueCefSharp) and [ChromelyAngularCefGlue](https://github.com/chromelyapps/demo-projects/tree/master/angular-react-vue/ChromelyAngularCefGlue) will help.

**Comment by Fiahblade** [comment]
I wanted to implement but has to stop due to lack of time. Might have a look at it again.
